### PR TITLE
Changed http to https

### PR DESCRIPTION
**Pull request by zeromido**
Changed http to https (to avoid redirections)
@drizt Thanks for the tip :)

### CODE REVIEW

**Comment by drizt** [comment]
Please use single commit, also do not close oldest PR. It is enough to always do

    git commit --amend
    git push --force

Also change commit message first line from `Changed http to https` to `Change http to https` and read https://github.com/agis-/git-style-guide#messages again.

**Comment by zeromido** [comment]
I don't know how to use git commands. Besides don't be so strict buddy LOL.

**Comment by drizt** [comment]
If you want to send PR's you need to learn how to use git.

**Comment by zeromido** [comment]
Sorry, want me to close it?

**Comment by drizt** [comment]
I don't. I mean that a pull request should be enough good quality. So you have 2 ways. First improve current pull request until enough good quality. Second open a new issue as you do before and ask me to fix this.

**Comment by zeromido** [comment]
Issue created.

**Pull request closed without merging**
