### PR TITLE
Changed http to https

### PR DESCRIPTION
**Pull request by zeromido**

### CODE REVIEW

**Comment by drizt** [comment]
Explain this changes. Also please try to follow [this](https://github.com/agis-/git-style-guide#messages) Git Commits Guide. 

> The summary line (ie. the first line of the message) should be descriptive yet succinct. Ideally, it should be no longer than 50 characters. It should be capitalized and written in imperative present tense. It should not end with a period since it is effectively the commit title:

**Comment by zeromido** [comment]
@drizt it's a very minor change, I don't think it needs a description. I changed it because when I opened the links with http it kept loading for while, before it was redirected to https.
I don't think this minor change can affect anything.

**Comment by drizt** [comment]
Do you mean you need wait extra time to open http link?

**Comment by zeromido** [comment]
Yeah. It took the browser a while to redirect me to the https link.

**Comment by drizt** [comment]
Ok. Then you're right. But there is one more issue. This change breaks translations. So also need to edit all .ts files.

**Pull request closed without merging**
